services:
  backend:
    image: moh080203/gold-backend:latest
    env_file:
      - .gold.env
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - database


  database:
    image: mysql:8.4.0
    env_file:
      - .gold.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gold_store